# Generated by Django 4.2.7 on 2024-01-06 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_otpcode_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 5, 47, 23, 657641, tzinfo=datetime.timezone.utc)),
        ),
    ]
