# Generated by Django 4.2.7 on 2024-01-14 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_otpcode_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 7, 23, 5, 544272, tzinfo=datetime.timezone.utc)),
        ),
    ]
