# Generated by Django 4.2.7 on 2023-12-19 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 17, 40, 38, 973528, tzinfo=datetime.timezone.utc)),
        ),
    ]
