# Generated by Django 4.2.7 on 2023-12-19 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otpcode_expired_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fist_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 19, 18, 43, 29, 193672, tzinfo=datetime.timezone.utc)),
        ),
    ]
