# Generated by Django 4.2.7 on 2023-12-25 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_otpcode_expired_at_alter_profile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 15, 19, 59, 912319, tzinfo=datetime.timezone.utc)),
        ),
    ]
