# Generated by Django 4.2.7 on 2023-12-25 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_otpcode_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 25, 15, 53, 11, 769764, tzinfo=datetime.timezone.utc)),
        ),
    ]
