# Generated by Django 4.2.7 on 2023-12-28 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vendors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('license_file', models.FileField(upload_to=vendors.models.vendor_path_file)),
                ('is_approved', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_user', to=settings.AUTH_USER_MODEL)),
                ('vendor_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to='accounts.profile')),
            ],
        ),
    ]
