# Generated by Django 4.2.7 on 2024-01-06 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.SmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('from_hour', models.CharField(blank=True, choices=[('00:00 AM', '00:00 AM'), ('00:30 AM', '00:30 AM'), ('01:00 AM', '01:00 AM'), ('01:30 AM', '01:30 AM'), ('02:00 AM', '02:00 AM'), ('02:30 AM', '02:30 AM'), ('03:00 AM', '03:00 AM'), ('03:30 AM', '03:30 AM'), ('04:00 AM', '04:00 AM'), ('04:30 AM', '04:30 AM'), ('05:00 AM', '05:00 AM'), ('05:30 AM', '05:30 AM'), ('06:00 AM', '06:00 AM'), ('06:30 AM', '06:30 AM'), ('07:00 AM', '07:00 AM'), ('07:30 AM', '07:30 AM'), ('08:00 AM', '08:00 AM'), ('08:30 AM', '08:30 AM'), ('09:00 AM', '09:00 AM'), ('09:30 AM', '09:30 AM'), ('10:00 AM', '10:00 AM'), ('10:30 AM', '10:30 AM'), ('11:00 AM', '11:00 AM'), ('11:30 AM', '11:30 AM'), ('12:00 PM', '12:00 PM'), ('12:30 PM', '12:30 PM'), ('13:00 PM', '13:00 PM'), ('13:30 PM', '13:30 PM'), ('14:00 PM', '14:00 PM'), ('14:30 PM', '14:30 PM'), ('15:00 PM', '15:00 PM'), ('15:30 PM', '15:30 PM'), ('16:00 PM', '16:00 PM'), ('16:30 PM', '16:30 PM'), ('17:00 PM', '17:00 PM'), ('17:30 PM', '17:30 PM'), ('18:00 PM', '18:00 PM'), ('18:30 PM', '18:30 PM'), ('19:00 PM', '19:00 PM'), ('19:30 PM', '19:30 PM'), ('20:00 PM', '20:00 PM'), ('20:30 PM', '20:30 PM'), ('21:00 PM', '21:00 PM'), ('21:30 PM', '21:30 PM'), ('22:00 PM', '22:00 PM'), ('22:30 PM', '22:30 PM'), ('23:00 PM', '23:00 PM'), ('23:30 PM', '23:30 PM')], null=True)),
                ('to_hour', models.CharField(blank=True, choices=[], null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendor')),
            ],
            options={
                'ordering': ('days',),
                'unique_together': {('vendor', 'days', 'from_hour', 'to_hour')},
            },
        ),
    ]
