# Generated by Django 4.2.7 on 2024-01-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='shipment',
            field=models.FloatField(default=0),
        ),
    ]
