# Generated by Django 4.2.7 on 2024-01-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_shipment',
            field=models.FloatField(default=0),
        ),
    ]
